### PR TITLE
resolved KeyError at /connect/get_token/ "given_name"

### PR DESCRIPTION
**Pull request by HammerMeetNail**
Hey, awesome repo! I tried to take it for a spin and kept getting an error in the get_token() view. It traced back to user_info['given_name'] not being available. Took a quick look and I only saw the following keys in user_info:

ver, amr, aud, iss, tid, name, unique_name, oid, upn, exp, iat, sub, nbf

After changing 'given_name' to 'name' everything resolved correctly. Let me know if you want this submitted another way. Thanks!

### CODE REVIEW

**Comment by martellaj** [comment]
Hm, that's super interesting. You used an Office 365 account to sign in, right? I think that's the only account you _can_ use, but I ask because my token looks like this (which I thought was default):

```
{  
   'nbf':1442329312,
   'tid':'xxx',
   'name':'Garth Fort',
   'given_name':'Garth',
   'upn':'GarthF@patsoldemo6.onmicrosoft.com',
   'aud':xxx',
   'sub':'xxx',
   'ver':'1.0',
   'oid':'xxx',
   'exp':1442333212,
   'unique_name':'GarthF@patsoldemo6.onmicrosoft.com',
   'family_name':'Fort',
   'amr':[  
      'pwd'
   ],
   'iss':'https://sts.windows.net/xxx/',
   'iat':1442329312
}
```

**Comment by HammerMeetNail** [comment]
Definitely an Office 365 account. Using the ID and Secret I created in Azure Active Directory. I notice you also have a field for family_name. I just double checked the user I have setup and both First Name and Last Name fields are blank. Perhaps they aren't included in user_info if blank? See attached. 

I'll update the fields and verify shortly. 

screen shot 2015-09-15 at 11 24 24 am

**Comment by martellaj** [comment]
Very interesting. Thanks for this feedback! We've been on the fence on whether to use name or email address for display purposes... I'm thinking I might do some kind of hybrid of checking if a given_name exists, and then defaulting to upn if not. If you're interested in making that change, feel free to submit a PR.

**Comment by martellaj** [comment]
We decided to strip the username from the UPN. Thanks for your feedback here! You just fixed an issue in a number of our repos!

**Comment by martellaj** [comment]
@DJO3, I just submitted a fix to this issue. If you get a chance, a confirmation that it solves the issue you found would be awesome. Thank you!

**Comment by HammerMeetNail** [comment]
@martellaj Confirmed! Issue resolved. Thanks!

**Pull request closed without merging**
